# AdvancedRTPQueue Configuration
# Version: 2.2

# General queue settings
queue:
  # Number of players required to be in queue before teleporting
  required-players: 2

  # Time in seconds before an inactive queue is cleared
  clear-interval: 300

  # Allow players to switch worlds when already in queue
  # If true, using /rtpqueue world <world> will move player from current queue to new world queue
  # If false, player must first leave the queue before joining a different world queue
  allow-world-switching: true

# Cooldown settings
cooldowns:
  # Global cooldown in seconds between queue joins (-1 to disable)
  queue-join: 60

  # Wait time in seconds before teleporting after match is found
  pre-teleport: 5

  # Per-world cooldown settings
  per-world-cooldown:
    enabled: false
    worlds:
      world: 120
      world_nether: 180
      world_the_end: 240

# Teleport settings
teleport:
  # Default world settings
  default-world: "world"
  default-world-display-name: "Overworld"

  # Teleport coordinate boundaries
  min-x: -500
  max-x: 500
  min-z: -500
  max-z: 500

  # Safety checks
  safe-teleport: true
  cancel-on-move: true
  max-teleport-attempts: 10

  # Allow using fallback locations (world spawn) when no safe random location found
  # If false, teleport will be cancelled if no random location can be found
  allow-fallback-locations: false

  # List of block types considered unsafe to teleport onto
  unsafe-blocks:
    - LAVA
    - WATER
    - CACTUS
    - CAMPFIRE
    - FIRE
    - MAGMA_BLOCK
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - SWEET_BERRY_BUSH
    - WITHER_ROSE
    - POWDER_SNOW

  # Multi-world support
  other-worlds:
    enabled: false
    worlds:
      nether:
        name: "world_nether"
        display-name: "Nether"
        permission: "rtpqueue.world.nether"
        min-x: -500
        max-x: 500
        min-z: -500
        max-z: 500
        safe-teleport: true
        max-teleport-attempts: 10
      end:
        name: "world_the_end"
        display-name: "The End"
        permission: "rtpqueue.world.end"
        min-x: -500
        max-x: 500
        min-z: -500
        max-z: 500
        safe-teleport: true
        max-teleport-attempts: 10

# Claim protection settings
claim-protection:
  enabled: true
  plugins:
    grief-prevention: true
    factions: true
    towny: true

# Messages
messages:
  # Queue messages
  join-queue: "&#00ff00✔ &aYou joined the queue."
  leave-queue: "&#ff0000❌ &cYou left the queue."
  already-in-queue: "&#ffa500⚠ &eYou're already in the queue!"
  not-in-queue: "&#ff4444⚠ &cYou're not in the queue."
  waiting-for-opponent: "&#0099ff⏳ &bWaiting for a match..."
  queue-cleared: "&#ff3300 &cQueue cleared."

  # Teleport messages
  opponent-found: "&#ff0000⚔ &cMatch found! Teleporting in {time} seconds with {players} players..."
  teleporting-title: "&#ff6600 &6Teleporting..."
  teleporting-subtitle: "&#ff3333 &cGet ready!"
  teleported: "&#00ff00✅ &aTeleported!"
  teleport-failed: "&#ff0000❌ &cTeleport failed! No safe spot."
  world-teleport: "&#00ccff &bTeleporting to {world}..."
  invalid-world: "&#ff0000⚠ &cError: Invalid world!"

  # Teleport cancellation messages
  teleport-cancelled: "&#ff6600⚠ &cTeleport cancelled!"
  move-cancelled: "&#ff6600⚠ &eTeleport cancelled! You moved during countdown."
  cancel-moved: "&#ff6600⚠ &eTeleport cancelled! You moved during countdown."
  cancel-left: "&#ff6600⚠ &cTeleport cancelled! You left the server."
  cancel-not-enough-players: "&#ff6600⚠ &cTeleport cancelled! Not enough players."
  cancel-no-safe-locations: "&#ff6600⚠ &cTeleport cancelled! No safe location found."
  cancel-invalid-world: "&#ff6600⚠ &cTeleport cancelled! Invalid world."

  # Group cancellation messages (sent to other players)
  group-teleport-cancelled: "&#ff6600⚠ &cTeleport cancelled because {player} {reason}!"
  group-cancel-moved: "&#ff6600⚠ &cTeleport cancelled because {player} moved!"
  group-cancel-left: "&#ff6600⚠ &cTeleport cancelled because {player} left!"

  # Other messages
  reload: "&#00cc00 &aConfig reloaded!"
  no-permission: "&#ff5555⛔ &cNo permission."
  cooldown-active: "&#ff9900⏱ &eOn cooldown. Try again in {time} seconds."
  invalid-command: "&#ff5500❓ &cUnknown command. Try &e/rtpqueue &cor &e/rtpqueue cancel."
  claim-protected: "&#ff3333 &cCannot teleport to claimed land."

# Sounds
sounds:
  queue-join: "ENTITY_EXPERIENCE_ORB_PICKUP"
  queue-cleared: "BLOCK_NOTE_BLOCK_BASS"
  opponent-found: "ENTITY_PLAYER_LEVELUP"
  teleport: "ENTITY_ENDERMAN_TELEPORT"
  error: "ENTITY_VILLAGER_NO"

# Debug mode - enable to see detailed logs in console
# Only necessary for troubleshooting issues
debug: false