# =====================================
#  AdvancedRTPQueue Configuration
# =====================================
# Configure queue size, teleport settings, messages, and sounds.

# ==========================
# Queue Settings
# ==========================
queue:
  required-players: 2      # Players needed to start teleportation
  clear-interval: 300      # Queue resets if inactive (seconds)

# ==========================
# Teleportation Settings
# ==========================
teleport:
  world: "world"
  min-x: -500
  max-x: 500
  min-z: -500
  max-z: 500
  safe-teleport: true       # Ensures safe landing spots
  max-teleport-attempts: 10 # Retries for safe teleport location
  spawn-radius: 5           # Radius within which players spawn

  # Unsafe blocks for teleportation
  unsafe-blocks:
    - LAVA
    - WATER
    - FIRE
    - CACTUS
    - MAGMA_BLOCK
    - VOID_AIR

# ==========================
# Messages
# ==========================
messages:
  join-queue: "&#00ff00✔ &aYou joined the queue."
  waiting-for-opponent: "&#0099ff⏳ &bWaiting for a match..."
  leave-queue: "&#ff0000❌ &cYou left the queue."
  already-in-queue: "&#ffa500⚠ &eYou're already in the queue!"
  not-in-queue: "&#ff4444⚠ &cYou're not in the queue."
  opponent-found: "&#ff0000⚔ &cMatch found! Teleporting..."
  teleporting-title: "&#ff6600🚀 &6Teleporting..."
  teleporting-subtitle: "&#ff3333🔥 &cGet ready!"
  teleported: "&#00ff00✅ &aTeleported!"
  no-permission: "&#ff5555⛔ &cNo permission."
  reload: "&#00cc00🔄 &aConfig reloaded!"
  queue-cleared: "&#ff3300🚀 &cQueue cleared."
  invalid-world: "&#ff0000⚠ &cError: Invalid world!"
  invalid-command: "&#ff5500❓ &cUnknown command. Try &e/rtpqueue &cor &e/rtpqueue cancel."
  teleport-failed: "&#ff0000❌ &cTeleport failed! No safe spot."

# ==========================
# Sounds
# ==========================
sounds:
  queue-join: ENTITY_PLAYER_LEVELUP
  teleport: ENTITY_ENDERMAN_TELEPORT
  error: ENTITY_VILLAGER_NO
  queue-cleared: ENTITY_ENDER_DRAGON_GROWL
  opponent-found: ENTITY_EXPERIENCE_ORB_PICKUP