# AdvancedRTPQueue v2.3 Configuration

# Plugin settings
plugin:
  # Debug mode - shows detailed information for troubleshooting
  debug: false

# Queue behavior settings
queue:
  # Number of players required before teleporting
  required-players: 2

  # Auto-clear inactive queues (seconds, 0 = disabled)
  clear-interval: 300

  # Allow players to switch worlds while queued
  allow-world-switching: true

  # Automatically join default world queue on login
  auto-join-on-login: false

# Cooldown system (all in seconds)
cooldowns:
  # Cooldown between queue joins
  queue-join: 60

  # Cooldown after leaving queue
  queue-leave: 10

  # Wait time before teleporting after match found
  pre-teleport: 5

  # Cooldown after successful teleport
  post-teleport: 120

  # Per-world cooldowns (optional)
  per-world-cooldown:
    enabled: false
    worlds:
      world: 120
      world_nether: 180

# Teleportation settings
teleport:
  # Default world configuration
  default-world: "world"
  default-world-display-name: "&aOverworld"

  # Coordinate boundaries for teleportation
  min-x: -1000
  max-x: 1000
  min-z: -1000
  max-z: 1000
  min-y: 60
  max-y: 250

  # Safety and behavior settings
  safe-teleport: true
  cancel-on-move: true
  cancel-on-damage: false
  cancel-on-chat: false
  max-teleport-attempts: 15

  # Async location finding settings
  async-location-search: true
  search-timeout: 30
  allow-fallback-locations: true

  # Location caching
  cache-safe-locations: true
  max-cached-locations: 10

  # Blocks that are unsafe to teleport on/near
  unsafe-blocks:
    - LAVA
    - WATER
    - CACTUS
    - CAMPFIRE
    - FIRE
    - MAGMA_BLOCK
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - SWEET_BERRY_BUSH
    - WITHER_ROSE
    - POWDER_SNOW
    - END_PORTAL
    - NETHER_PORTAL

  # Additional worlds configuration
  other-worlds:
    enabled: true
    worlds:
      nether:
        name: "world_nether"
        display-name: "&cThe Nether"
        permission: "rtpqueue.world.nether"
        min-x: -500
        max-x: 500
        min-z: -500
        max-z: 500
        min-y: 30
        max-y: 120
        safe-teleport: true
        max-teleport-attempts: 20
      end:
        name: "world_the_end"
        display-name: "&dThe End"
        permission: "rtpqueue.world.end"
        min-x: -200
        max-x: 200
        min-z: -200
        max-z: 200
        min-y: 50
        max-y: 120
        safe-teleport: true
        max-teleport-attempts: 25

# Claim protection integration
claim-protection:
  enabled: true
  check-destination: true
  check-source: false
  plugins:
    grief-prevention: true
    factions: true
    towny: true

# User Interface settings
ui:
  # Message prefix for all plugin messages
  prefix: "&8[&6RTP Queue&8] &r"

  # Messages that should NOT have prefix
  no-prefix-messages:
    - "teleporting-title"
    - "teleporting-subtitle"
    - "countdown-title"
    - "countdown-subtitle"

  # Progress bar configuration
  progress-bar:
    enabled: true
    character: "▌"
    length: 20
    completed-color: "&a"
    remaining-color: "&7"

  # Action bar settings
  action-bar:
    enabled: true
    queue-wait: "&7Waiting for players... &e{current}&7/&e{required}"
    countdown: "&6Teleporting in &c{time} &6seconds..."
    update-interval: 20

# Title and subtitle configuration
titles:
  queue-joined:
    title: "&6Queue Joined"
    subtitle: "&7Waiting for &e{required} &7players"
    fade-in: 10
    stay: 40
    fade-out: 10

  match-found:
    title: "&aMatch Found!"
    subtitle: "&7Teleporting in &c{time} &7seconds"
    fade-in: 5
    stay: 30
    fade-out: 10

  countdown:
    title: "&c{time}"
    subtitle: "&7Get ready..."
    fade-in: 0
    stay: 25
    fade-out: 5

  teleported:
    title: "&aTeleported!"
    subtitle: "&7Good luck exploring!"
    fade-in: 10
    stay: 30
    fade-out: 20

# All plugin messages
messages:
  # Queue messages
  join-queue: "&aYou joined the &e{world} &aqueue! &7({current}/{required})"
  leave-queue: "&cYou left the queue."
  already-in-queue: "&eYou're already in the &6{world} &equeue!"
  not-in-queue: "&cYou're not in any queue."

  # Status messages
  waiting-for-players: "&7Waiting for &e{needed} &7more player(s)..."
  queue-status: "&7Queue Status: &e{current}&7/&e{required} &7players"
  position-in-queue: "&7You are &e#{position} &7in the queue."

  # Teleportation messages
  match-found: "&aMatch found! Teleporting in &c{time} &aseconds with &e{players} &aplayers..."
  teleport-starting: "&6Preparing teleportation..."
  teleporting: "&7Teleporting to &e{world}&7..."
  teleported: "&aTeleported successfully to &e{world}&a!"
  teleport-failed: "&cTeleport failed! No safe location found."

  # Cancellation messages
  cancelled-moved: "&cTeleport cancelled! You moved during countdown."
  cancelled-left: "&cTeleport cancelled! You disconnected."
  cancelled-damage: "&cTeleport cancelled! You took damage."
  cancelled-chat: "&cTeleport cancelled! You chatted during countdown."
  cancelled-not-enough: "&cTeleport cancelled! Not enough players remaining."
  cancelled-error: "&cTeleport cancelled due to an error."
  cancelled-timeout: "&cTeleport cancelled! Location search timed out."
  cancelled-no-safe-locations: "&cTeleport cancelled! No safe locations found."
  cancelled-invalid-world: "&cTeleport cancelled! Invalid world."
  cancelled-shutdown: "&cTeleport cancelled! Server is shutting down."

  # Group cancellation message
  group-cancelled: "&cTeleport cancelled because &e{player} &c{reason}!"

  # Cooldown messages
  cooldown-active: "&eYou must wait &c{time} &eseconds before using this again."
  cooldown-queue-join: "&eYou must wait &c{time} &eseconds before joining a queue."
  cooldown-post-teleport: "&eYou must wait &c{time} &eseconds before teleporting again."

  # Error messages
  no-permission: "&cYou don't have permission to do that."
  invalid-world: "&cInvalid world: &e{world}"
  world-not-loaded: "&cWorld &e{world} &cis not loaded."
  no-permission-world: "&cYou don't have permission to teleport to &e{world}&c."
  player-not-found: "&cPlayer &e{player} &cnot found."
  invalid-command: "&cInvalid command usage. Type &e/rtpqueue &cfor help."

  # Admin messages
  reload-success: "&aConfiguration reloaded successfully!"
  reload-failed: "&cFailed to reload configuration: &e{error}"
  force-queue-success: "&aForced &e{player} &ainto &e{world} &aqueue."
  force-queue-failed: "&cFailed to force &e{player} &cinto queue: &e{reason}"
  queue-cleared: "&cAll queues have been cleared by an administrator."

  # Statistics messages
  stats-header: "&7&m----------&r &6Queue Statistics &7&m----------"
  stats-total-players: "&7Total queued players: &e{total}"
  stats-your-world: "&7Your queue (&e{world}&7): &e{current}&7/&e{required}"
  stats-world-line: "&7{world}: &e{current}&7/&e{required} &7players"
  stats-footer: "&7&m----------------------------------------"

  # Protection messages
  location-claimed: "&cCannot teleport to claimed land."
  source-protected: "&cYou cannot teleport from this protected area."

# Sound effects configuration
sounds:
  enabled: true

  queue-join:
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0
    pitch: 1.0

  queue-leave:
    sound: "ENTITY_ITEM_BREAK"
    volume: 0.7
    pitch: 0.8

  match-found:
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.2

  countdown:
    sound: "BLOCK_NOTE_BLOCK_PLING"
    volume: 0.8
    pitch: 1.5

  teleport-success:
    sound: "ENTITY_ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0

  teleport-cancelled:
    sound: "ENTITY_VILLAGER_NO"
    volume: 0.8
    pitch: 0.9

  error:
    sound: "BLOCK_ANVIL_LAND"
    volume: 0.5
    pitch: 0.8

# Particle effects configuration
particles:
  enabled: true

  teleport-start:
    particle: "PORTAL"
    count: 50
    spread: 1.0

  teleport-success:
    particle: "EXPLOSION_NORMAL"
    count: 20
    spread: 0.5

# Advanced settings
advanced:
  # Async operations thread pool size
  async-thread-pool: 4

  # Cache settings
  location-cache-size: 100
  player-cache-timeout: 300

  # Performance settings
  max-concurrent-searches: 5
  search-chunk-limit: 100

  # Logging settings
  log-teleports: true
  log-queue-actions: false