# AdvancedRTPQueue v3.0 Configuration
# =====================================
# Professional RTP Queue system with safe teleportation
# NOTE: per-world cooldowns use BUKKIT world names (see cooldowns.per-world-cooldown.worlds).

plugin:
  debug: false

queue:
  required-players: 2
  clear-interval: 300            # seconds between automatic queue clear maintenance runs
  allow-world-switching: true
  auto-join-on-login: false

cooldowns:
  queue-join: 60                 # global join cooldown (seconds)
  queue-leave: 10                # leave cooldown (seconds)
  pre-teleport: 5                # countdown before teleport (seconds)
  post-teleport: 120             # cooldown after being teleported (seconds)
  per-world-cooldown:
    enabled: false
    # Use Bukkit world names here (not display names). Example names below:
    worlds:
      world: 120                 # overworld (bukkit name)
      world_nether: 180          # nether (bukkit name)
      world_the_end: 180         # end (bukkit name)

teleport:
  default-world: "world"                         # Bukkit world name used as default
  default-world-display-name: "&aOverworld"      # Display name used in messages/tab
  min-x: -1000
  max-x: 1000
  min-z: -1000
  max-z: 1000
  min-y: 60
  max-y: 250
  safe-teleport: true
  cancel-on-move: true
  cancel-on-damage: false
  cancel-on-chat: false
  max-attempts: 100
  search-timeout: 45
  cache-safe-locations: true
  max-cached-locations: 15
  allow-fallback-locations: true
  unsafe-blocks:
    - LAVA
    - WATER
    - CACTUS
    - CAMPFIRE
    - FIRE
    - MAGMA_BLOCK
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - SWEET_BERRY_BUSH
    - WITHER_ROSE
    - POWDER_SNOW
    - END_PORTAL
    - NETHER_PORTAL
    - VOID_AIR
    - CAVE_AIR
  other-worlds:
    enabled: true
    worlds:
      nether:
        # config key: "nether" (used in commands and tab). bukkit name below:
        name: "world_nether"
        display-name: "&cThe Nether"
        permission: "rtpqueue.world.nether"
        min-x: -500
        max-x: 500
        min-z: -500
        max-z: 500
        min-y: 30
        max-y: 120
        max-attempts: 75
      end:
        name: "world_the_end"
        display-name: "&dThe End"
        permission: "rtpqueue.world.end"
        min-x: -200
        max-x: 200
        min-z: -200
        max-z: 200
        min-y: 50
        max-y: 120
        max-attempts: 50

claim-protection:
  enabled: true
  plugins:
    grief-prevention: true
    factions: true
    towny: true

ui:
  action-bar:
    enabled: true
    update-interval: 20
    queue-wait: "&7Waiting for &e{needed} &7more player(s)... &7(&e{current}&7/&e{required}&7)"
    countdown: "&6Teleporting in &c{time} &6seconds..."

titles:
  queue-joined:
    title: "&6Queue Joined"
    subtitle: "&7Waiting for &e{needed} &7more player(s)"
    fade-in: 10
    stay: 40
    fade-out: 10

  match-found:
    title: "&aMatch Found!"
    subtitle: "&7Teleporting in &c{time} &7seconds"
    fade-in: 5
    stay: 30
    fade-out: 10

  countdown:
    title: "&c{time}"
    subtitle: "&7Get ready..."
    fade-in: 0
    stay: 25
    fade-out: 5

  teleported:
    title: "&aTeleported!"
    subtitle: "&7Good luck exploring!"
    fade-in: 10
    stay: 30
    fade-out: 20

messages:
  # Basic queue messages
  join-queue: "&a✔ You joined the &e{world} &aqueue! &7({current}/{required})"
  leave-queue: "&c❌ You left the queue."
  already-in-queue: "&e⚠ You're already in the queue!"
  not-in-queue: "&c⚠ You're not in the queue."
  match-found: "&a🎯 Match found! Teleporting in &c{time} &aseconds..."
  teleporting: "&6🚀 Teleporting to &e{world}&6..."
  teleported: "&a✅ Successfully teleported!"
  no-permission: "&c⛔ No permission."
  no-permission-world: "&c⛔ No permission for world &e{world}&c."
  invalid-world: "&c⚠ Invalid world: &e{world}"
  invalid-command: "&c❓ Usage: &e/rtpqueue [world <name>|leave|reload|clear|force <player> [world]]"
  invalid-player: "&c⚠ Player &e{player} &cis not online."

  # Reload / admin
  reload-success: "&a🔄 Configuration reloaded!"
  reload-failed: "&c❌ Reload failed: &e{error}"
  queue-cleared: "&c🧹 All queues cleared."

  # Teleport cancellations / failures
  teleport-failed: "&c❌ Teleport failed! No safe location found."
  cancelled-moved: "&c❌ Teleport cancelled - you moved!"
  cancelled-damage: "&c❌ Teleport cancelled - you took damage!"
  cancelled-chat: "&c❌ Teleport cancelled - you chatted!"
  cancelled-timeout: "&c❌ Teleport cancelled - location search timed out!"
  cancelled-shutdown: "&c❌ Teleport cancelled - server restarting!"

  # Cooldowns
  cooldown-active: "&c⏰ Cooldown active! Wait &e{time}&c."
  cooldown-queue-join: "&c⏰ Queue join cooldown! Wait &e{time}&c."
  cooldown-post-teleport: "&c⏰ Post-teleport cooldown! Wait &e{time}&c."

  # Force command messages (administrative)
  force-added-player: "&a✔ Added &e{player} &ato the &e{world} &aqueue."
  forced-added: "&a✔ You were added to the &e{world} &aqueue by an admin."
  force-switched-player: "&a✔ Moved &e{player} &ato the &e{world} &aqueue."
  force-player-already-in-queue: "&e⚠ &e{player} &eis already in the queue for &e{world}."
  force-failed: "&c❌ Failed to add &e{player} &cto the &e{world} &cqueue."
  force-switch-disabled: "&c⚠ Cannot move player — world switching for queued players is disabled."
  force-success: "&a✔ Forced action completed for &e{player} &7(&e{world}&7)."

sounds:
  enabled: true
  queue-join:
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0
    pitch: 1.0
  queue-leave:
    sound: "ENTITY_ITEM_BREAK"
    volume: 0.7
    pitch: 0.8
  match-found:
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.2
  countdown:
    sound: "BLOCK_NOTE_BLOCK_PLING"
    volume: 0.8
    pitch: 1.5
  teleport-success:
    sound: "ENTITY_ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0
  teleport-cancelled:
    sound: "ENTITY_VILLAGER_NO"
    volume: 0.8
    pitch: 0.9
  error:
    sound: "BLOCK_ANVIL_LAND"
    volume: 0.5
    pitch: 0.8

particles:
  enabled: true
  teleport-start:
    particle: "PORTAL"
    count: 50
    spread: 1.0
  teleport-success:
    particle: "EXPLOSION_NORMAL"
    count: 20
    spread: 0.5

advanced:
  log-queue-actions: false
  log-teleports: true