name: AdvancedRTPQueue
version: "3.0"
main: com.kingrbxd.rtpqueue.AdvancedRTPQueue
author: KingRBxD
description: Professional Random Teleportation Queue system with safe teleportation
api-version: 1.19
softdepend: [GriefPrevention, Factions, Towny, PlaceholderAPI, PaperLib]

commands:
  rtpqueue:
    description: Join or manage the RTP queue
    usage: /rtpqueue [world <name>|leave|reload|clear]
    permission: rtpqueue.use
    aliases: [rtpq, rtp]

permissions:
  rtpqueue.use:
    description: Basic queue access
    default: true
  rtpqueue.admin:
    description: Admin commands (reload, clear)
    default: op
  rtpqueue.bypass.cooldown:
    description: Bypass all cooldowns
    default: op
  rtpqueue.world.*:
    description: Access to all worlds
    default: op